root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/explorer ./cmd/in-network-explorer"
  bin = "./tmp/explorer preview"
  include_ext = ["go", "gohtml"]
  exclude_dir = ["tmp", "vendor", ".git", "docs", "scripts"]
  exclude_regex = ["_test\\.go$"]
  delay = 500

[log]
  time = false

[misc]
  clean_on_exit = true
